title: "[Showcase] "
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief summary of what is being showcased.
    validations:
      required: true
  - type: textarea
    id: preview 
    attributes:
      label: Images / Preview
      description: Some Images showing off the project, or links to e.g. a demo repository.
    validations:
      required: true
