name: 🐛 Bug Report
description: Report a bug in the current version of saucer
labels: ["bug"]
assignees: Curve

body:
  - type: textarea
    attributes:
      label: ✍️ Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔁 Steps to reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: 🔗 Reproduction Example
      description: If applicable, please provide a reproduction example. This can either be a code-snippet or a link to a repository. 
    validations:
      required: false

  - type: textarea
    attributes:
      label: ❔ Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: 👀 Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: input
    attributes:
      label: 🛸 Saucer Version
      description: Please state the version of saucer this bug occurs on.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 🖥️ Operating System
      description: The operating system the problem occurred on.
      options:
        - Linux
        - MacOS
        - Windows 10
        - Windows 11
        - Other (Please specify)
    validations:
      required: true

  - type: input
    attributes:
      label: 🧰 Compiler
      description: The exact compiler (and compiler version) used. You can typically find this information in the CMake output.
    validations:
      required: true

  - type: input
    attributes:
      label: 📦 Environment
      description: The exact WebView2 / Qt / Webkit version that is installed on the system.
    validations:
      required: true

  - type: input
    attributes:
      label: 🖥️ Distribution
      description: If applicable, please state the Linux Distribution or Windows-Build Number here.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: ✅ I confirm that...
      description: Please confirm these things by clicking the checkboxes
      options:
        - label: I have collected all the required information and read all the comments in this document
          required: true
        - label: I searched for an existing bug report for this issue
          required: true
        - label: The problem does occur with the reproduction steps I provided
          required: true
