on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Test Qt6 (Release)
jobs:
  test-qt6-release:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "pacman --noconfirm -Syu base-devel cmake gcc git make qt6-base qt6-declarative qt6-positioning xorg-server-xvfb qt6-svg qt6-tools qt6-translations qt6-webchannel qt6-webengine"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dsaucer_tests=ON -Dsaucer_backend=Qt6 && cmake --build . --config Release"

      - name: Run Tests
        run: 'QTWEBENGINE_DISABLE_SANDBOX=1 xvfb-run "./build/saucer_tests"'
