on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Test WebView2
jobs:
  test-webview2:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dsaucer_tests=ON -Dsaucer_backend=WebView2 && cmake --build . --config Debug"

      # TODO: The Windows workflow currently doesn't work on GitHub. Not sure why but it works locally.
      # - name: Run Tests
      # run: 'D:\\a\\saucer\\saucer\\build\\Debug\\saucer_tests.exe'
